новый cicd

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -10,32 +10,27 @@ jobs:
   build:
     runs-on: ubuntu-latest
 
-    services:
-      rabbitmq:
-        image: rabbitmq:3-management
-        ports:
-          - 5672:5672
-
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
 
       - name: Set up Python
-        uses: actions/checkout@v4
+        uses: actions/setup-python@v5
         with:
           python-version: '3.10'
 
       - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
-          pip install -r app/requirements.txt
-          pip install -r cart/requirements.txt
-          pip install -r orders/requirements.txt
+          [ -f app/requirements.txt ] && pip install -r app/requirements.txt || echo "app/req not found"
+          [ -f cart/requirements.txt ] && pip install -r cart/requirements.txt || echo "cart/req not found"
+          [ -f orders/requirements.txt ] && pip install -r orders/requirements.txt || echo "orders/req not found"
 
       - name: Build with Docker Compose
         run: docker compose build
 
       - name: Run with Docker Compose
         run: |
-          docker compose up -d  
-          docker compose ps      
+          docker compose up -d
+          sleep 10
+          docker compose ps
